### ISSUE TITLE
Mostrar etapa actual de vacunacion

### ISSUE THREAD

**Issue by abejaranoh** [ikks/ikks.github.io#2]
De acuerdo al minsalud, existen diferentes etapas de vacunación (I ... V) dependiendo de los grupos de riesgo, edad, etc. Es posible mostrar esta información tambien?

**Comment by ikks** [comment]
Hola, cómo te imaginas la proyección de esta información? Lo que tenemos proyectado para hacer en poco tiempo es la información de Etapa 1 y la etapa final.

Gracias !

**Comment by ikks** [comment]
Creo que hemos capturado lo que nos contabas @abejaranoh , por supuesto que eres bienvenido a hacer pull requests :)
